### ISSUE TITLE
El nombre del paquete debe ser relevante (1 décima)

### ISSUE THREAD

**Issue by gfhuertac** [Kromtar/prueba0_lyp#2]
No usar nombres que hubiesen sido conflictivos. Por ejemplo, ¿qué pasaría si la prueba tuviera 2 preguntas? ¿subirías todo al mismo paquete a pesar de ser temas distintos?

**Comment by Kromtar** [comment]
Solucionado en  87b003a

Objeción (Si, soy muy hostigoso en estas cosas jaja):
1) Esto se basa meramente en suposiciones. Si la prueba tuviese 2 preguntas seria necesario realizar este cambio de crear 2 paquetes independientes, o en caso de 3 preguntas tener 3 paquetes; pero solo tiene 1 pregunta. Osea es aleatorio pre-considerar que puedan existir mas preguntas.
2) También podríamos considerar correcto agregar nuestro nombre `cl.uai.prueba0_lyp.pregunta1.federico` ya que el mismo problema esta siendo solucionado por varias personas de maneras diferentes. O subdividir el paquete para ordenar de forma mejor las clases `.pregunta1.pintas`. Osea si no se predefine con anterioridad que tan especifico es necesario ser con los paquetes o que se consideren casos como la posible existencia de mas preguntas o identificadores por nombres o secciones .... resulta fuera del pedido del problema que esta en el Readme (el cual dice "ordenar las clases en paquetes" solamente).
3) Lo correcto también podría ser `cl.uai.tics_200.prueba0_lyp.pregunta1.federico` ...

**Comment by gfhuertac** [comment]
Relevante me refería al tema.
cl.uai.tics200.naipe
es más concordate que
cl.uai.tics200.prueba0
que no refleja en nada lo pedido, y reutilizarlo en el futuro con ese nombre no serviría.

Tampoco calza la solución con tu nombre, porque en una organización hay muchos autores.
Los nombres de paquete no son para distinguir autores.

**Comment by Kromtar** [comment]
Entendido, corregido nuevamente en 735d55c

Yo ocupe `cl.uai.prueba0_lyp` en una primera instancia basándome en la prueba de practica: https://github.com/gfhuertac/lyp 
donde se ocupa ese paquete `cl.uai.lyp` como paquete ejemplo. Por tanto inferí que para esta prueba tendría que ocuparse `cl.uai.prueba0_lyp` y posiblemente para la próxima `cl.uai.prueba1_lyp`

Aunque no logro comprender algo. Ahora si cada persona que dio la prueba ocupa el paquete `cl.uai.tics200.naipe` (el cual use yo y supongo que es una solución valida), no generaría una especie de choque al momento de implementarlos?  En este caso donde muchas personas están trabajando en lo mismo no habría que hacer un identificación con el nombre si mas de uno ocupa lo mismo ?

Saludos.

**Comment by gfhuertac** [comment]
Es que esa es la gracia de usar git :)
Tu habilitas un branch o fork en particular para probar cosas. Activas el de uno o del otro. Cuando algo está bien usas un merge y lo subes a la rama principal.

**Comment by Kromtar** [comment]
Gracias por las respuesta a ambas Issues, me gusta quedar claro con los errores para no cometerlos otra vez.
