### ISSUE TITLE
Los constructores de la subclase deben recibir UN parámetro solamente (8 décimas)

### ISSUE THREAD

**Issue by gfhuertac** [Kromtar/prueba0_lyp#3]
Por ejemplo

Carta carta = new Trebol(numero)
es correcto

Carta carta = new Trebol(TREBOL, numero)
es incorrecto

**Comment by Kromtar** [comment]
Arreglado en 4abb632

Objeción al puntaje -8 décimas:
Encuentro que es muy severa la reducción de puntos por:
1) Yo NO tengo `Carta carta = new Trebol(TREBOL, numero)` sino `Carta carta = new Trebol(Pinta.TREBOL, numero)`; osea si me limito a ocupar el enum de Pintas.java y su contenido. Solo que en vez de ocupar el enum de Pinta dentro del `super` de una clase extendida de Carta lo ocupo en los parámetros al instancia la Crata respectiva.
2) Mi código compila y funciona correctamente en al versión 85b1f70 (entregada al final de la prueba). 
3) Aunque comprendo que esta mejor encapsulado la utilización del contenido de Pinta.java en el constructor de la carta, porque al fin  al cabo es una especia de constante. Considere que era mas fácil, en caso de querer agregar mas pintas o variantes de cartas en un futuro, pasar el parámetro como argumento para su instancia.

Saludos !

**Comment by gfhuertac** [comment]
El punto 1 en tu comentario es lo mismo
Carta carta = new Trebol(TREBOL, numero) ES Carta carta = new Trebol(Pinta.TREBOL, numero); 
(import Pinta.TREBOL mediante :) )
El punto 2, que compile, pero que no siga lo pedido, causa más problemas que no compile pero que siga lo pedido, ya que al menos el resto de la gente puede seguir trabajando en el proyecto porque las interfaces se han respetado. El descuento de puntaje no es porque no es grave en la compilación, sino por lo serio de no seguir lo señalado.
Y el punto 3 discrepo, pues al crear nuevas pintas igual debes crear nuevas clases y es más fácil dejar fija la pinta en la clase que andar escribiéndola en cada una de las creaciones de instancias de esas clases.

**Comment by Kromtar** [comment]
Oks
